name: absensi_rangkai_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cool_alert: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  get: 4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  latlong2: ^0.8.1
  location: ^4.3.0
  safe_device: ^1.1.1
  camera: ^0.9.4+14
  file_picker: ^4.4.0
  flutter_native_image: ^0.0.6+1
  mime: ^1.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
